#pragma once

namespace Imgn
{
	enum EntityData
	{
		MAX_ENTITIES = 500,
		MAX_COMPONENTCLASS = 500,
		NUM_COLLIDERS = 5,
		MAX_COMPONENTS_PERENTITY = 10,
		MAX_NAME_LEN = 30,
		MAX_VARIABLES = 100,
		MAX_SAME_COMPONENT = 100
	};
}
